### ISSUE TITLE
 Warning: Remote connection disconnect. Retrying...

### ISSUE THREAD

**Issue by nassajis** [markush81/kafka-cluster#1]
hi guys

![untitled](https://user-images.githubusercontent.com/10128882/43993249-b1fe4754-9d9f-11e8-8a74-6cc16b4e4c47.jpg)

**Comment by markush81** [comment]
yep, this is a common Vagrant issue ... how does it end? Cause for me it does work, but takes a long time until vagrant connects.

https://github.com/hashicorp/vagrant/issues/9416
